### ISSUE TITLE
safari: the row hovering stay stuck on the last row

### ISSUE THREAD

**Issue by nimeshpokhrel** [jmlemetayer/abba#27] opened 2022-05-04 09:51 UTC
Last item is selected even when I click on the first one:

![See here](https://cdn.discordapp.com/attachments/630323379458670594/971348173341749278/Screen_Shot_2022-05-04_at_3.34.34_PM.png)

**Comment by jmlemetayer** [comment] 2022-05-04 10:13
Hi Nimesh,

What do you want to say by "last item is selected" ? Is it the gray background and the underline ?

It should be working "on hover" and not "on click". This is working for me on the previews: https://jmlemetayer.github.io/abba/previews/default/

And when you have directories, a click on a row should go to the requested directory.

Is it not working for you? What is your browser and version?

**Comment by nimeshpokhrel** [comment] 2022-05-04 10:21
I am using safari latest version

Even when I hover on the first, second or any item last item gets highlighted in grey color and same is clicked even if my pointer is on first item

**Comment by nimeshpokhrel** [comment] 2022-05-04 10:27
Ok the issues is only on safari
Just checked works perfect on other browser

**Comment by jmlemetayer** [comment] 2022-05-04 12:27
Yeah I have also tested on safari and I see the issue too. The hovering effect stay stuck on the last item.

Moreover I have tested the [bootstrap](https://getbootstrap.com/docs/5.1/content/tables/#hoverable-rows) and [bootswatch](https://bootswatch.com/default/#tables) examples on safari. They seems to be working.

Thanks for the report.

**Comment by nimeshpokhrel** [comment] 2022-05-04 12:34
Do fix this soon if you can gotta work with the site. Thanks in advance

**Comment by Egleyser** [comment] 2022-05-14 05:32
Hi!
The same happens to me in both Safari and Chrome using the Solar theme: The last item is selected even when I click on the first. Tested from different devices and browsers.

By the way nice work friend, congratulations, everything I was looking for days :)

**Comment by digicide** [comment] 2022-05-18 17:11
the a::after pseudo element is position absolute. It seems like it expects the offset parent to be the td, but the td is not set as such. So the offset parent becomes the entire table, and the last a::after on the page fills its offset parent, which is the entire table.

I fixed this in my copy by adding position: relative to td, explicitly making it the offset parent.

**Comment by jmlemetayer** [comment] 2022-05-18 20:16
Thanks @digicide it helps a lot.

Since the problem is not reproduced with the standard bootstrap, I think I made a mistake in the integration of the `.table-hover` class. Or maybe the [`.stretched-link`](https://getbootstrap.com/docs/5.1/helpers/stretched-link/) ...

> See: https://github.com/jmlemetayer/abba/blob/main/_sass/abba/_autoindex.scss

**Comment by jmlemetayer** [comment] 2022-05-18 20:18
If you have some free time. Pull requests are more than welcome :wink:

**Comment by Egleyser** [comment] 2022-05-21 12:01
Hi guys, information I think is important for the case. In the tests I did, the mentioned bug only occurs in browsers (Safari, Chrome, Firefox, Opera, among others) for IOS. For any other browser on Android this problem does not occur.

**Comment by jmlemetayer** [comment] 2022-11-06 21:52
Hi all,

I am trying to integrate the new bootstrap 5.2.2 version. Since this was not a simple integration and there was some work to be done, I decided to look at this problem at the same time.

So I tried to reproduce the issue first, and I didn't succeed !!!

Since I didn't have time to update ABBA, it can only be Safari. With version 16.0 it works, can you confirm?

It also works with Chrome (107.0.5304.87) on macOS (11.7).

**Comment by Egleyser** [comment] 2022-11-07 02:49
> Olá a todos,
> 
> Estou tentando integrar a nova versão bootstrap 5.2.2. Como essa não era uma integração simples e havia algum trabalho a ser feito, decidi analisar esse problema ao mesmo tempo.
> 
> Então tentei reproduzir o problema primeiro, e não consegui!!!
> 
> Como não tive tempo de atualizar o ABBA, só pode ser Safari. Com a versão 16.0 funciona, pode confirmar?
> 
> Também funciona com o Chrome (107.0.5304.87) no macOS (11.7).
Hello friend,
I just tested on IOS (Chrome, Safari, Opera) and the same problem remains.

**Comment by jmlemetayer** [comment] 2022-11-07 09:26
Hi @Egleyser Thanks for the feedback.

Can you tell me your macOS version and browser versions ? Thanks

**Comment by Egleyser** [comment] 2022-11-07 12:45
Yes;
- IOS 15.5
- Chrome 107.0.5304.66
- Safari native of IOS 15.5
- Opera 3.3.8

Later I can test on IOS 16 and report back here.

**Comment by jmlemetayer** [comment] 2022-11-07 13:09
From what I saw yesterday, this is a problem with the `stretched-link` class and `table` in general.

See: https://getbootstrap.com/docs/5.2/helpers/stretched-link/
> Please note given [how CSS position works](https://www.w3.org/TR/CSS21/visuren.html#propdef-position), .stretched-link cannot be mixed with most table elements.

Currently, ABBA uses the last example with the `transform: rotate(0)`. But I want to try the suggestion from here:
https://github.com/twbs/bootstrap/issues/28608#issuecomment-614881795

I will create a `abba-next` project so you can have some GitHub pages to test. I'll post the link when it's ready (hopefully tonight).

Best regards.

**Comment by jmlemetayer** [comment] 2022-11-07 21:36
Hi @Egleyser,

I have created the `abba-next` project. You can see the previews here:
https://jmlemetayer.github.io/abba-next/previews/default/

I have use the proposed method and add a green background to see the area covered by the stretched link. I will adjust this later.

It is working for me. Can you test on your side ?

Thanks in advance.

**Comment by jmlemetayer** [comment] 2022-11-09 08:01
Happy to hear that !

I will test another thing before updating the upstream project: Use the same mechanism but on the full row (and not just on one cell).

BTW I will not be able to update to 5.2.2 because there is an issue with the sketchy theme which have been resolved by this commit https://github.com/thomaspark/bootswatch/commit/ca48826d04b656cf23d90f440a751cf220928472 after the `v5.2.2` tag. So I will wait until the next bootswatch release to do the update. Let's hope there will be a `v5.2.2+1`.

**Comment by jmlemetayer** [comment] 2022-11-09 20:02
Hi @Egleyser,

I tested expanding the link to the entire row. It works for me.
But if we believe the bootstrap bug mentioned above, it may not work for you. Can you test it ?

Once again, thank you very much for your help!

**Comment by Egleyser** [comment] 2022-11-10 00:52
@jmlemetayer It didn't work for me.

**Comment by jmlemetayer** [comment] 2022-11-10 08:11
Hi,

Ok, I was expecting that.

I have final solution, that I kept last, because it is less clean. But that should work.

I'll keep you updated.

**Comment by jmlemetayer** [comment] 2022-11-15 20:44
Hi @Egleyser,

It took a while, but it seems to work this time. [Can you confirm that it works?](https://jmlemetayer.github.io/abba-next/previews/default/)

Best regards.

**Comment by jmlemetayer** [comment] 2022-11-16 08:08
Fixed :blush: !

Thanks everybody, and especially @Egleyser for your help.

**Closed by jmlemetayer** 2022-11-16 08:08 UTC
Labels: bug
